### ISSUE TITLE
DNSMASQ支持通配符，我觉得列表可以精简一下。

### ISSUE THREAD

**Issue by codexss** [JJaicmkmy/CMCC-DNSMasq#1]
比如这个格式
address=/.zune.net/96.7.54.113
address=/.xboxlive.net/96.7.54.113
address=/.xbox.com/210.192.109.20

**Comment by jichizhang** [comment]
确实，因为当初是直接从 hosts 转换成 DNSMasq 的，所以没有做优化，我会改的。另外这样做有一点风险，比如如果这样配置
address=/.baidu.com/119.75.217.109
会导致 pan.baidu.com，tieba.baidu.com等如果不在配置文件中，则都会被解析到119.75.217.109，然后就会产生错误。所以估计精简的过程挺复杂的。

**Comment by LGA1150** [comment]
googleusercontent.com googleapis.com 都是泛域名解析的
（需要排除 *.l.googleusercontent.com *.storage.googleapis.com *.commondatastorage.googleapis.com *.c.bigcache.googleapis.com）

**Comment by jichizhang** [comment]
@LGA1150 服务器上已更新，配置文件稍后更新。

**Comment by codexss** [comment]
还有gvt1.com也是泛解析，Google play的apk下载的host
