### ISSUE TITLE
The resolution of code.jquery.com makes Udacity or other website too slow to be opened.

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [JJaicmkmy/CMCC-DNSMasq#4]
可能因为code.jquery.com在大陆被封的原因，Udacity之类需要用到code.jquery,com的网站打开得特别慢。可否新增一条code.jquery.com的记录
网页有以下行的会打开得特别慢

<script src="/standalone/libs/jquery-1.10.2.min.js" type="text/javascript" ></script>

**Comment by MitsuhaMiyamizu** [comment]
应该是移动的墙封的，而非GFW，所以应该可以解决?

**Comment by jichizhang** [comment]
刚回到家，已 fix，服务器上稍后更新。
